// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using alldux_plataforma.Data;

namespace alldux_plataforma.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20211004164026_MigrationAzure01")]
    partial class MigrationAzure01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("alldux_plataforma.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("alldux_plataforma.Models.BrasindiceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sucess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("BrasindiceLog");
                });

            modelBuilder.Entity("alldux_plataforma.Models.BrasindicePF", b =>
                {
                    b.Property<string>("TISS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApresentacaoCod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApresentacaoNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("EAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdicaoAltPreco")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagPisCofins")
                        .HasColumnType("TEXT");

                    b.Property<string>("Generico")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPI")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaboratorioCod")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaboratorioNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentoCod")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentoNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoFracionado")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoTipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("QtdFracionamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("TUSS")
                        .HasColumnType("TEXT");

                    b.HasKey("TISS");

                    b.ToTable("BrasindicePF");
                });

            modelBuilder.Entity("alldux_plataforma.Models.BrasindicePMC", b =>
                {
                    b.Property<string>("TISS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApresentacaoCod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApresentacaoNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("EAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdicaoAltPreco")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagPisCofins")
                        .HasColumnType("TEXT");

                    b.Property<string>("Generico")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPI")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaboratorioCod")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaboratorioNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentoCod")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentoNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoFracionado")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoTipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("QtdFracionamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("TUSS")
                        .HasColumnType("TEXT");

                    b.HasKey("TISS");

                    b.ToTable("BrasindicePMC");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiretrizesClinicasId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretrizesClinicasId");

                    b.ToTable("DiretrizModulo");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiretrizesClinicasId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoProtocolo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretrizesClinicasId")
                        .IsUnique();

                    b.ToTable("DiretrizPrecificadas");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificadaRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CicloTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiasCiclo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiretrizPrecificadaTabelaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoseFinal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medicamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mgm2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ordem")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScPeso")
                        .HasColumnType("TEXT");

                    b.Property<string>("TISS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorCiclo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorCpMgAlldux")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretrizPrecificadaTabelaId");

                    b.ToTable("DiretrizPrecificadaRegistro");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificadaTabela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveTabela")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiretrizPrecificadaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Finalidade")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Linha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretrizPrecificadaId");

                    b.ToTable("DiretrizPrecificadaTabela");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizSecao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bibliografia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DiretrizModuloId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretrizModuloId");

                    b.ToTable("DiretrizSecao");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizesClinicas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lead")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiretrizesClinicas");
                });

            modelBuilder.Entity("alldux_plataforma.Models.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pergunta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resposta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Faq");
                });

            modelBuilder.Entity("alldux_plataforma.Models.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeGenerico")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipioAtivo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("alldux_plataforma.Models.MedicamentoVariacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Biossimilar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distribuidor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Familia")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Generico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Laboratorio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Padronizado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrecoAlldux")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoMercado")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Referencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subclasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("TISS")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnApresentacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnApresentacaoTipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnMedida")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnMedidaTipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("MedicamentoVariacao");
                });

            modelBuilder.Entity("alldux_plataforma.Models.Negociacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestaqueCurto")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestaqueLongo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastUpdateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Obs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parceiro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Negociacao");
                });

            modelBuilder.Entity("alldux_plataforma.Models.NegociacaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NegociacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoAlternativo")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoDesconto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NegociacaoId");

                    b.ToTable("NegociacaoItem");
                });

            modelBuilder.Entity("alldux_plataforma.Models.TNUMM", b =>
                {
                    b.Property<string>("TISS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApresentacaoBrasindice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CNPJRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classe")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataFimImplantacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataFimVigencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescBrasindice")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetentorRegistroAnvisa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Generico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grupo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoInsercao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeApresentacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Obs")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecoMaxNacional")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipioAtivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistroAnvisa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TISSBrasindice")
                        .HasColumnType("TEXT");

                    b.Property<string>("TISSCodAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("TISSTP")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxaCustos")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCodificacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoProduto")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidMinFracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorFatorConversao")
                        .HasColumnType("TEXT");

                    b.HasKey("TISS");

                    b.ToTable("TNUMM");
                });

            modelBuilder.Entity("alldux_plataforma.Models.BrasindiceLog", b =>
                {
                    b.HasOne("alldux_plataforma.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizModulo", b =>
                {
                    b.HasOne("alldux_plataforma.Models.DiretrizesClinicas", "DiretrizesClinicas")
                        .WithMany("DiretrizModulo")
                        .HasForeignKey("DiretrizesClinicasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiretrizesClinicas");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificada", b =>
                {
                    b.HasOne("alldux_plataforma.Models.DiretrizesClinicas", "DiretrizesClinicas")
                        .WithOne("DiretrizPrecificada")
                        .HasForeignKey("alldux_plataforma.Models.DiretrizPrecificada", "DiretrizesClinicasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiretrizesClinicas");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificadaRegistro", b =>
                {
                    b.HasOne("alldux_plataforma.Models.DiretrizPrecificadaTabela", "DiretrizPrecificadaTabela")
                        .WithMany("DiretrizPrecificadaRegistro")
                        .HasForeignKey("DiretrizPrecificadaTabelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiretrizPrecificadaTabela");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificadaTabela", b =>
                {
                    b.HasOne("alldux_plataforma.Models.DiretrizPrecificada", "DiretrizPrecificada")
                        .WithMany("DiretrizPrecificadaTabela")
                        .HasForeignKey("DiretrizPrecificadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiretrizPrecificada");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizSecao", b =>
                {
                    b.HasOne("alldux_plataforma.Models.DiretrizModulo", "DiretrizModulo")
                        .WithMany("DiretrizSecao")
                        .HasForeignKey("DiretrizModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiretrizModulo");
                });

            modelBuilder.Entity("alldux_plataforma.Models.MedicamentoVariacao", b =>
                {
                    b.HasOne("alldux_plataforma.Models.Medicamento", "Medicamento")
                        .WithMany("Variacoes")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("alldux_plataforma.Models.NegociacaoItem", b =>
                {
                    b.HasOne("alldux_plataforma.Models.Negociacao", "Negociacao")
                        .WithMany("NegociacaoItem")
                        .HasForeignKey("NegociacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negociacao");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizModulo", b =>
                {
                    b.Navigation("DiretrizSecao");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificada", b =>
                {
                    b.Navigation("DiretrizPrecificadaTabela");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizPrecificadaTabela", b =>
                {
                    b.Navigation("DiretrizPrecificadaRegistro");
                });

            modelBuilder.Entity("alldux_plataforma.Models.DiretrizesClinicas", b =>
                {
                    b.Navigation("DiretrizModulo");

                    b.Navigation("DiretrizPrecificada");
                });

            modelBuilder.Entity("alldux_plataforma.Models.Medicamento", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("alldux_plataforma.Models.Negociacao", b =>
                {
                    b.Navigation("NegociacaoItem");
                });
#pragma warning restore 612, 618
        }
    }
}
